apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: home.vimll.com:5000/nginx 
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 800M
            cpu: 500m
          requests:
            memory: 400Mi
            cpu: 128m
status: {}
