apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: nginxv1
  name: nginxv1
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      run: nginxv1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginxv1
    spec:
      containers:
      - image: home.vimll.com:5000/nginx:v1 
        name: nginxv1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 800M
          requests:
            memory: 400Mi
status: {}
